import type { Metadata } from "next";
import { ContentPage } from "@/components/content-page";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of WillBee’s Will-generation service. This is not legal advice.",
  alternates: { canonical: "/terms-of-service" },
};

export default function TermsPage() {
  return (
    <ContentPage
      title="Terms of Service"
      intro="Please read these terms carefully before using WillBee."
    >
      <h2>1. What WillBee is</h2>
      <p>
        WillBee is a self-service tool that helps you generate a Last Will and
        Testament structured for the law of Scotland, based on the answers you
        provide. <strong>WillBee is not a law firm and does not provide legal
        advice.</strong> Using WillBee does not create a solicitor–client
        relationship.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You may only use WillBee if you are aged 12 or over, domiciled in
        Scotland, and have the mental capacity to make a Will. You are responsible
        for the accuracy of the information you provide.
      </p>

      <h2>3. Validity of your Will</h2>
      <p>
        A Will generated by WillBee is only legally valid once it has been printed
        and properly signed and witnessed in accordance with the signing
        instructions we provide. We are not responsible for any Will that is not
        correctly executed.
      </p>

      <h2>4. Limitations</h2>
      <p>
        WillBee is designed for straightforward estates. If your circumstances are
        complex (for example, business interests, trusts, overseas assets, or
        contentious family situations), you should consult a Scottish solicitor.
      </p>

      <h2>5. Payment and refunds</h2>
      <p>
        The service is provided for a one-off fee shown at checkout. Because the
        document is generated and delivered immediately, the fee is generally
        non-refundable once the document has been produced, except where required
        by law.
      </p>

      <h2>6. Liability</h2>
      <p>
        To the fullest extent permitted by law, WillBee’s liability is limited to
        the amount you paid for the service. We do not accept liability for losses
        arising from incorrect information you provide or from a Will that is not
        properly signed and witnessed.
      </p>

      <h2>7. Contact</h2>
      <p>Questions about these terms? Email {SITE.supportEmail}.</p>
    </ContentPage>
  );
}
